name: Docker Build, Test and Deploy

on:
  push:
    branches: [main, test-branch]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [main, test-branch]

env:
  IMAGE_NAME: json_validator
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/json_validator

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
    
    - name: Run server in background
      run: |
        python server.py &
        echo $! > server.pid
        sleep 3  # Даем серверу время на запуск
    
    - name: Run tests
      run: |
        python -m pytest -v test_server.py
    
    - name: Stop server
      if: always()
      run: |
        kill $(cat server.pid) || true

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.DOCKERHUB_REPO }}:latest